import os
import struct
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class FirmwareRebuilder:
    """Rebuilds and verifies UEFI firmware images, recalculating checksums where possible."""

    def __init__(self):
        pass

    def rebuild(self, firmware_path: str, output_path: str) -> None:
        """Rebuild firmware image and recalculate checksums."""
        logger.info(f"Loading firmware image from {firmware_path}")
        
        with open(firmware_path, "rb") as f:
            firmware = bytearray(f.read())

        logger.info(f"Firmware size: {len(firmware)} bytes ({hex(len(firmware))})")

        # Identify firmware type and rebuild accordingly
        if self._is_uefi_firmware(firmware):
            logger.info("Detected UEFI firmware format")
            self._rebuild_uefi(firmware)
        else:
            logger.warning("Could not definitively identify firmware type; performing basic rebuild...")
            self._rebuild_generic(firmware)

        with open(output_path, "wb") as f:
            f.write(firmware)
        logger.info(f"Rebuilt firmware written to {output_path}")
        
        # Verify rebuilt image
        self._verify_firmware(firmware)
        
        # Generate flashrom command
        self._generate_flashrom_command(output_path)

    def _generate_flashrom_command(self, firmware_path: str) -> None:
        """Generate flashrom command for flashing the rebuilt firmware."""
        # Detect programmer (this is a heuristic - in real use, user would specify)
        programmers = ["ch341a_spi", "dediprog", "internal"]  # Common ones
        
        # For demonstration, use ch341a_spi as mentioned in the spec
        programmer = "ch341a_spi"
        
        command = f"flashrom -p {programmer} -w {firmware_path}"
        logger.info("Generated flashrom command:")
        logger.info(f"  {command}")
        logger.warning("WARNING: Flashing firmware can brick your device if done incorrectly!")
        logger.warning("Make sure you have a backup and know what you're doing.")
        
        # Save command to file
        cmd_file = firmware_path + ".flashrom_cmd"
        with open(cmd_file, 'w') as f:
            f.write(f"# Flashrom command for {firmware_path}\n")
            f.write(f"# Generated by UEFI Sanitizer Tool\n")
            f.write(f"# WARNING: Use at your own risk!\n")
            f.write(f"{command}\n")
        
        logger.info(f"Flashrom command saved to: {cmd_file}")

    def _is_uefi_firmware(self, firmware: bytearray) -> bool:
        """Check if firmware is UEFI format."""
        # Look for UEFI Firmware Volume Header
        signatures = [b"_FVH_", b"_FVE_", b"$FID"]
        return any(sig in firmware[:0x10000] for sig in signatures)

    def _rebuild_uefi(self, firmware: bytearray) -> None:
        """Rebuild UEFI firmware, recalculating checksums."""
        offset = 0
        volumes_found = 0
        
        while offset < len(firmware) - 32:
            if firmware[offset : offset + 4] == b"_FVH":
                volumes_found += 1
                logger.info(f"Found UEFI Firmware Volume Header at {hex(offset)}")
                self._fix_fv_checksum(firmware, offset)
            offset += 1

        logger.info(f"Found and fixed {volumes_found} UEFI Firmware Volume headers")

    def _fix_fv_checksum(self, firmware: bytearray, fv_offset: int) -> None:
        """Recalculate checksum for a UEFI Firmware Volume."""
        try:
            # Parse FV header (simplified)
            if fv_offset + 32 > len(firmware):
                logger.warning(f"Firmware too short to parse FV at {hex(fv_offset)}")
                return

            # FV header structure: signature(4) + attributes(4) + size(8) + blockmap(8) + ...
            fv_size_offset = fv_offset + 20
            if fv_size_offset + 4 <= len(firmware):
                fv_size = struct.unpack("<I", firmware[fv_size_offset : fv_size_offset + 4])[0]
                
                if fv_offset + fv_size <= len(firmware):
                    fv_region = firmware[fv_offset : fv_offset + fv_size]
                    checksum = self._calculate_checksum_8(fv_region)
                    
                    # Update checksum field at offset 26
                    checksum_offset = fv_offset + 26
                    if checksum_offset + 1 <= len(firmware):
                        firmware[checksum_offset] = checksum & 0xFF
                        logger.info(f"Updated FV checksum at {hex(checksum_offset)} to {hex(checksum)}")
        except Exception as e:
            logger.warning(f"Could not fix FV checksum at {hex(fv_offset)}: {e}")

    def _rebuild_generic(self, firmware: bytearray) -> None:
        """Perform generic rebuild (minimal operations)."""
        logger.info("Performing generic firmware rebuild (minimal checksums)")
        # Generic rebuild mainly validates structure, detailed checksum logic would go here

    def _verify_firmware(self, firmware: bytearray) -> None:
        """Verify rebuilt firmware integrity."""
        logger.info("Verifying rebuilt firmware...")
        
        # Check for suspicious patterns
        suspicious = [b"MALWARE", b"ROOTKIT", b"ESP32"]
        found_suspicious = False
        
        for sig in suspicious:
            if sig in firmware:
                logger.error(f"SUSPICIOUS PATTERN DETECTED: {sig}")
                found_suspicious = True
        
        if not found_suspicious:
            logger.info("✓ No obvious suspicious patterns detected")

        # Check firmware size
        size_mb = len(firmware) / (1024 * 1024)
        if 0.5 <= size_mb <= 16:
            logger.info(f"✓ Firmware size is reasonable: {size_mb:.2f} MB")
        else:
            logger.warning(f"⚠ Firmware size is unusual: {size_mb:.2f} MB")

        logger.info("Firmware verification complete")

    @staticmethod
    def _calculate_checksum_8(data: bytes) -> int:
        """Calculate 8-bit checksum (sum of all bytes mod 256)."""
        checksum = sum(data) & 0xFF
        return (0x100 - checksum) & 0xFF
